version: '2'
services:
  chatbot:
    user: root
    image: node:16
    restart: unless-stopped
    volumes:
      - ./:/web/
    working_dir: /web
    command: 'sh -c "npm i && npm run dev"'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./storage/postgresql:/var/lib/postgresql
    ports:
    - 6543:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
